language: swift
xcode_workspace:  Example/openxcframework.xcworkspace
xcode_scheme: openxcframework-Example
os: osx
podfile: Example/
stages:
- name: run-builds
- name: deploy
  if: branch = master
  
jobs:
  - stage: run-builds
    osx_image: xcode11.3
    script:
    - gem install cocoapods
    - pod repo update
    - cd Example/
    - pod deintegrate
    - pod install
    - cd ../
    - xcodebuild test -enableCodeCoverage YES -workspace Example/openxcframework.xcworkspace -scheme openxcframework-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=YES -destination "platform=iOS Simulator,OS=13.0,name=iPhone 11 Pro"

  - stage: run-builds
    osx_image: xcode10.3
    script:
    - gem install cocoapods
    - pod repo update
    - cd Example/
    - pod deintegrate
    - pod install
    - cd ../
    - xcodebuild test -enableCodeCoverage YES -workspace Example/openxcframework.xcworkspace -scheme openxcframework-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=YES -destination "platform=iOS Simulator,OS=12.0,name=iPhone X"

  - stage: run-builds
    osx_image: xcode9.4
    script:
    - gem install cocoapods
    - pod repo update
    - cd Example/
    - pod deintegrate
    - pod install
    - cd ../
    - xcodebuild test -enableCodeCoverage YES -workspace Example/openxcframework.xcworkspace -scheme openxcframework-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=YES -destination "platform=iOS Simulator,OS=11.4,name=iPhone X"

  - stage: run-builds
    osx_image: xcode8.3
    script:
    - gem install cocoapods
    - pod repo update
    - cd Example/
    - pod deintegrate
    - pod install
    - cd ../
    - xcodebuild test -enableCodeCoverage YES -workspace Example/openxcframework.xcworkspace -scheme openxcframework-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=YES -destination "platform=iOS Simulator,OS=10.0,name=iPhone SE"

  - stage: deploy
    script:
    - gem install cocoapods
    - pod repo update
    - cd Example/
    - pod install
    - cd ../
    - pod trunk push --verbose | ruby -e 'ARGF.each{ print "." }'
    
#- pod spec lint openxcframework.podspec  --allow-warnings
#- pod trunk push openxcframework.podspec --allow-warnings -verbose | ruby -e 'ARGF.each{print "." }'
