# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage


language: swift
osx_image: xcode10.2
xcode_project:  Example/openxcframework.xcworkspace
xcode_scheme: openxc-ios-framework
xcode_sdk: iphonesimulator12.0
os: osx

branches:
- master
- next

# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - name: deploy
#   if: branch =~ ^\d+\.\d+\.\d+$
# -- set -o pipefail &&

- ENV['COCOAPODS_TRUNK_TOKEN'] = sh "grep -s password ~/.netrc | awk '{print $2}'"
- gem install cocoapods # Since Travis is not always on latest version
- pod repo update

script:
- xcodebuild test -enableCodeCoverage YES -workspace Example/openxcframework.xcworkspace -scheme openxcframework-Example -sdk iphonesimulator12.0 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod spec lint openxcframework.podspec  --allow-warnings
- pod trunk push openxcframework.podspec --allow-warnings -verbose | ruby -e 'ARGF.each{print "." }'




