name: Deploy

on: 
 push:
  branches:
   - master

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Cocopods
      run: |
        gem install cocoapods
        pod repo update
        cd Example/
        pod install
        cd ../
    - name: Push Pod
      run: pod trunk push --verbose | ruby -e 'ARGF.each{ print "." }'
