name: Swift

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Cocopods
      run: |
        gem install cocoapods
        pod repo update
        cd Example/
        pod deintegrate
        pod install
        cd ../
    - name: Force xcode 11
      run: sudo xcode-select -switch /Applications/Xcode_11.7.app
    - name: Test on iPhone 11 Pro
      run: |
        xcodebuild test -enableCodeCoverage YES -workspace Example/openxcframework.xcworkspace -scheme openxcframework-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=YES -destination "platform=iOS Simulator,OS=13.7,name=iPhone 11 Pro"
    - name: Test on iPhone X
      run: |
        xcodebuild test -enableCodeCoverage YES -workspace Example/openxcframework.xcworkspace -scheme openxcframework-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=YES -destination "platform=iOS Simulator,OS=13.7,name=iPhone X"
